version: '3.7'

services:

  redis:
    image: redis:alpine
    restart: always
    command: redis-server
    volumes:
      - general_redis_data:/data
    ports:
      - "6379:6379"
    container_name: redis
    networks:
      - musicnet

networks:
  musicnet:
    external: true

volumes:
  general_redis_data:
