# Generated by Django 4.1.4 on 2024-02-27 20:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequestEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failure', 'Failure'), ('ready', 'Ready'), ('done', 'Done')], default='pending', max_length=32)),
                ('songID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'search_request',
            },
        ),
    ]
